### ISSUE TITLE
edlib

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/text_search#2]
Guys, for the Levenshtein edit distance part, I am thinking about using this code:
https://github.com/Martinsos/edlib
I am reading about it right now.  License is MIT so very flexible.
It supports Levenshtein alignment of long sequences, also, using an algorithm that is quadratic in time but only linear in memory.
(We'd incorporate the C++ code into this project, probably.)

**Comment by danpovey** [comment]
... OK, so I'm thinking the minimum viable product (MVP) for this, and the thing we should aim for, is the task where we have as "reference" text the utf-8 text of a Project Gutenberg book, and as "query" text, several different chapter recordings from a LibriVox audio book.
Then what we do is:
 - Load the reference and multiple query texts into a single SourcedText object
 - Apply some normalizations on the SourcedText object, such as removing multiple spaces and removing punctuation, while keeping track of the source byte locations.
 - Use the suffix array stuff, and find_candidate_matches or whatever it was called, to locate the approximate region in the book text corresponding roughly to the chapter.
 - Call code from edlib to align each chapter (the "query") to the selected region of the Gutenberg text.  (Note: we'll use the 'infix' version of alignment, so it will truncate the region of reference text to just the matching region.)
 [I'm going to edit this in a minute to talk about what happens next, i.e. how we represent the alignment and what the ultimate output of the program will be.]

**Comment by pkufool** [comment]
Great!  For the edlib, we just copy the source files we need from their repo or add it as dependancy via cmake?

**Comment by danpovey** [comment]
I think better to copy source files.   We can acknowledge it in our LICENSE.txt
