### ISSUE TITLE
Idea for finding traceback quickly

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/text_search#21]
Guys,

 I have an idea for how we could quickly obtain an alignment from the suffix-array stuff.

 This version would make the most sense if it was done from one single long sequence to another,
 e.g. from one book to an entire chapter.

 A previous algorithm whose name I forget, gave us a set of "close matches" obtained from
 a suffix array algorithm.

 Let us think of these "close matches" as a set of (i, j) pairs, where i is an index into
 one sequence and j is an index into the other.

 We can define a task of getting an approximate alignment between the two sequences,
 as the task of finding the longest chain of pairs:
   (i1, j1), (i2, j2), ... (iN, jN)

 such that i1 <= i2 <= ... <= iN, and j1 <= j2 <= ... <= jN.

 One way that we could do this is as follows:
    First sort the list of pairs on (i, then j).
    Then, for each pair p == (i, j) in the sorted list, set
       count[p] = 1 + max_q(count[q])
    where q is taken from all previously processed pairs, but limited to those
    where q.i <= p.i and q.j <= p.j.  (treating them like pairs in python,
    so [0] and [1] return the i and j values).  We can take the "max" expression
    to be 0 if there is no q satisfying these constraints

 Then when we are done processing all pairs, the last element in the longest-chain is the
 pair with the largest count.  We can store "back-pointers" for each processed pair
 to tell us which previous pair satisfied the "max" expression.

 Now, the above algorithm is quadratic on the face of it, but I think in C++ we can make it
 n log(n), by making use of the properties of std::set, as follows.

Sets are ordered by default in C++, i.e. a std::set is stored in sorted order, but with efficient
insertion.  Concretely, the algorithm would be like this.  I'll just use int as the type; you can decide
what to use.
```
  // these GoodMatch items, at least the i and j elements,
  //  are an input, they are sorted on (i, then j).  The index into this list
  // is n.

  struct GoodMatch {
    int i;  // position of "good match" in 1st sequence
    int j;  // position of "good match" in 2nd sequence
    int prev_n;  // previous n in backtrace, index into list of GoodMatch.  set in the algorithm.
    bool operator < (const GoodMatch &other) const {  // sort on i, then j.
       if (i < other.i) return true;
       else if (i > other.i) return false;
       else return j < other.j;
       // note: could perhaps do this more efficiently using << and |, not sure if
       // it matters.
  };

  // sort this by i, then j.  prev_n values can be undefined for now.
  std::vector<GoodMatch> sorted_input;  // this is created somehow, then sorted.

  struct GoodMatchCount {
    int j;
    int n;
    int c;
    bool operator < (const GoodMatchCount &other) const {
       if (j < other.j) return true;
       else if (j > other.j) return false;
       else return n < other.n;
    }
  };


  // in addition to being sorted on j, the counts will always have the
  // property that the c values are strictly increasing.  We ensure this
  // by removing elements as necessary.
  std::set<GoodMatchCount> cur_counts;
  cur_counts.insert(GoodMatchCount(0, -1, 0));

  int N = sorted_pairs.size();
  for (int n = 0; n < N; ++n) {
    int j = sorted_pairs[n].j;
    GoodMatchCount gmc(j, n, 0);  // the 0 is a don't-care, we'll set it later.
    auto p = cur_counts.insert(gmc);  // p is pair (iterator, bool)
    assert(p.second);  // should have been inserted, should not be present.
    auto iter = p.first, prev_iter = p.first;
    --prev_iter;  // now points to the previous element, should have prev_iter->j <= j.
    // we know prev_iter->i <= sorted_pairs[n].i, because sorted_pairs are sorted on i.
    int c = prev_iter->c + 1;
    sorted_pairs[n].prev_n = prev_iter->n; // backtrace for newly added element.
    iter->c = c;
    ++iter;
    // Erase all the elements gmc with gmc.j > j and gmc.count <= c:
    // for these j values, the count value is not as good as the one we just
    // added so we'll never want to backtrace to them.
    cur_counts.erase(p.first, iter);
  }

  // After we have done iterating, we can get the "best traceback"
  // as the final element of cur_counts, e.g. cur_counts.back(),
  // and trace back using the prev_n member.
```
The idea is that we can use the traceback through these "good matches" as the backbone for the Levenshtein alignment, so that
we limit the Levenshtein alignment into blocks defined by the (i, j) positions in this traceback.  (Whether we use the maximum possible number of blocks or not, I'm not sure.)

**Comment by pkufool** [comment]
Closed via https://github.com/k2-fsa/text_search/pull/27
