### ISSUE TITLE
Support renumbering in create_suffix_array

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/text_search#24]
https://github.com/danpovey/text_search/blob/9499196e16b0a5bc32bebaa8ecdfaeefbb094598/textsearch/python/textsearch/suffix_array.py#L45

The above max_symbol affects directly how much memory is allocated below
https://github.com/danpovey/text_search/blob/9499196e16b0a5bc32bebaa8ecdfaeefbb094598/textsearch/csrc/suffix_array.cc#L43
where `K` is `max_symbol`.

We should renumber the elements so that max_symbol equals to number of unique elements plus 1.

**Comment by pkufool** [comment]
Closed via https://github.com/k2-fsa/text_search/pull/25
