### ISSUE TITLE
Example usage docs; update docs

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/text_search#36]
Guys,
I was under the impressoion that we had committed some kind of examples for how you would use this end-to-end for aligning data where you have the reference and the approximate recognition, but I don't see anything like that... and the documentation seems to be only for the very first things we added?  I think this aspect needs some work at some point.  Or @pkufool maybe you have things that are not committed?
Dan

**Comment by pkufool** [comment]
Yes, the docs has not been merge, it is in this PR https://github.com/k2-fsa/text_search/pull/29 , will merge it.
