### ISSUE TITLE
Can't download librilight-text

### ISSUE THREAD

**Issue by shuaijiang** [k2-fsa/text_search#55]
Is this repo(https://huggingface.co/datasets/pkufool/librilight-text) broken?

**Comment by danpovey** [comment]
seems there may be an issue with a virus checker flagging it -- probably falsely.  kangwei or someone will have a look when he has time.

**Comment by pkufool** [comment]
I think it has nothing wrong with huggingface repo, I can download it just now. If huggingface is not available for you, you can download it from modelscope (git clone https://www.modelscope.cn/datasets/pkufool/librilight-text.git)
